"""Constants for the vidoes app"""

VIDEO_STATUS_DRAFT = 'D'
VIDEO_STATUS_PUBLISHED = 'P'
VIDEO_STATUS_ARCHIVED = 'A'
VIDEO_STATUS_CHOICES = (
    (VIDEO_STATUS_DRAFT,'Draft',),
    (VIDEO_STATUS_PUBLISHED,'Published',),
    (VIDEO_STATUS_ARCHIVED,'Archived',),
)

